version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      npm-minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: deps
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      actions:
        patterns: ["*"]
    commit-message:
      prefix: ci
